In [9]:
from scipy import sparse
import numpy as np

# Create a 2D NumPy array with a diagonal of ones, and zeros everywhere else
eye = np.eye(4)

print("NumPy array:\n{}".format(eye))

NumPy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
